import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalProvider from "./globalprovider";
import Modalcart from "@/Modal/modalcart";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Perfume",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
         <GlobalProvider>
          <main>{children?children:<div>Loading...</div>}</main>
         <Modalcart/>
        </GlobalProvider>
      
      </body>
    </html>
  );
}
